import type { AuctionItem } from '@/types/auction'

export const sampleAuctionItems: AuctionItem[] = [
  {
    id: '1',
    case_number: '2024타경50737',
    court: '대전지방법원 천안지원',
    property_type: '아파트',
    address: '충남 천안시 서북구 불당동 1234',
    region: '충남',
    city: '천안시',
    apartment_name: '불당 아이파크',
    dong: '102동',
    floor: 14,
    area_m2: 84.92,
    area_pyeong: 25,
    appraisal_price: 500000000,
    minimum_price: 240000000,
    fail_count: 2,
    auction_date: '2025-01-15',
    discount_rate: 52,
    turnover_rate: 4.1,
    required_investment: 45000000,
    is_safe: true,
    risk_factors: [],
    source_url: 'https://www.hauction.co.kr/item/1',
    image_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    case_number: '2024타경61245',
    court: '춘천지방법원',
    property_type: '아파트',
    address: '강원 춘천시 퇴계동 567',
    region: '강원',
    city: '춘천시',
    apartment_name: '그린타운',
    dong: '102동',
    floor: 4,
    area_m2: 118.5,
    area_pyeong: 36,
    appraisal_price: 320000000,
    minimum_price: 156800000,
    fail_count: 2,
    auction_date: '2025-01-20',
    discount_rate: 51,
    turnover_rate: 5.2,
    required_investment: 32000000,
    is_safe: true,
    risk_factors: [],
    source_url: 'https://www.hauction.co.kr/item/2',
    image_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    case_number: '2024타경52881',
    court: '수원지방법원 평택지원',
    property_type: '아파트',
    address: '경기 평택시 세교동 890',
    region: '경기',
    city: '평택시',
    apartment_name: '세교 푸르지오',
    dong: '205동',
    floor: 8,
    area_m2: 74.5,
    area_pyeong: 22,
    appraisal_price: 380000000,
    minimum_price: 195200000,
    fail_count: 1,
    auction_date: '2025-01-18',
    discount_rate: 49,
    turnover_rate: 4.8,
    required_investment: 38000000,
    is_safe: true,
    risk_factors: [],
    source_url: 'https://www.hauction.co.kr/item/3',
    image_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    case_number: '2024타경49203',
    court: '창원지방법원',
    property_type: '아파트',
    address: '경남 김해시 내동 123',
    region: '경남',
    city: '김해시',
    apartment_name: '김해 힐스테이트',
    dong: '107동',
    floor: 12,
    area_m2: 99.2,
    area_pyeong: 30,
    appraisal_price: 420000000,
    minimum_price: 218400000,
    fail_count: 1,
    auction_date: '2025-01-22',
    discount_rate: 48,
    turnover_rate: 3.9,
    required_investment: 42000000,
    is_safe: true,
    risk_factors: [],
    source_url: 'https://www.hauction.co.kr/item/4',
    image_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    case_number: '2024타경55123',
    court: '대구지방법원',
    property_type: '아파트',
    address: '대구 수성구 범어동 456',
    region: '대구',
    city: '수성구',
    apartment_name: '범어 자이',
    dong: '103동',
    floor: 20,
    area_m2: 134.8,
    area_pyeong: 41,
    appraisal_price: 680000000,
    minimum_price: 340000000,
    fail_count: 2,
    auction_date: '2025-01-25',
    discount_rate: 50,
    turnover_rate: 3.5,
    required_investment: 68000000,
    is_safe: true,
    risk_factors: [],
    source_url: 'https://www.hauction.co.kr/item/5',
    image_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    case_number: '2024타경58901',
    court: '부산지방법원',
    property_type: '아파트',
    address: '부산 해운대구 우동 789',
    region: '부산',
    city: '해운대구',
    apartment_name: '해운대 엘시티',
    dong: '101동',
    floor: 35,
    area_m2: 145.2,
    area_pyeong: 44,
    appraisal_price: 950000000,
    minimum_price: 475000000,
    fail_count: 2,
    auction_date: '2025-01-28',
    discount_rate: 50,
    turnover_rate: 2.8,
    required_investment: 95000000,
    is_safe: true,
    risk_factors: [],
    source_url: 'https://www.hauction.co.kr/item/6',
    image_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// 필터 적용 함수
export function filterAuctionItems(
  items: AuctionItem[],
  filters: {
    minTurnoverRate: number
    maxInvestment: number
    failCountFilter: number[]
    safeOnly: boolean
  }
): AuctionItem[] {
  return items.filter(item => {
    // 회전율 필터
    if (item.turnover_rate < filters.minTurnoverRate) return false

    // 실투자금 필터
    if (item.required_investment > filters.maxInvestment) return false

    // 유찰 횟수 필터
    const itemFailCount = item.fail_count >= 3 ? 3 : item.fail_count
    if (!filters.failCountFilter.includes(itemFailCount)) return false

    // 안전 물건 필터
    if (filters.safeOnly && !item.is_safe) return false

    return true
  })
}
